version: '3.8'

services:
  db: 
    image: postgres:latest
    container_name: my_postgres_auth
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - my_network
      
volumes:
  pg_data:

networks:
  my_network: